name: Backend - Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore EasyTalkForKids_server.sln

      - name: Build
        run: dotnet build EasyTalkForKids_server.sln --no-restore

      - name: Run unit tests
        run: dotnet test --filter Category=Unit
